VkPipelineDynamicStateCreateFlags :: VkFlags;
VkPipelineMultisampleStateCreateFlags :: VkFlags;
VkPipelineRasterizationStateCreateFlags :: VkFlags;
VkPipelineViewportStateCreateFlags :: VkFlags;
VkPipelineTessellationStateCreateFlags :: VkFlags;
VkPipelineInputAssemblyStateCreateFlags :: VkFlags;
VkPipelineVertexInputStateCreateFlags :: VkFlags;
VkBufferViewCreateFlags :: VkFlags;
VkDeviceCreateFlags :: VkFlags;
VkSemaphoreCreateFlags :: VkFlags;
VkShaderModuleCreateFlags :: VkFlags;
VkMemoryUnmapFlagsKHR :: VkMemoryUnmapFlags;
VkDescriptorPoolResetFlags :: VkFlags;
VkGeometryFlagsNV :: VkGeometryFlagsKHR;
VkGeometryInstanceFlagsNV :: VkGeometryInstanceFlagsKHR;
VkBuildAccelerationStructureFlagsNV :: VkBuildAccelerationStructureFlagsKHR;
VkPrivateDataSlotCreateFlagsEXT :: VkPrivateDataSlotCreateFlags;
VkDescriptorUpdateTemplateCreateFlags :: VkFlags;
VkDescriptorUpdateTemplateCreateFlagsKHR :: VkDescriptorUpdateTemplateCreateFlags;
VkPipelineCreationFeedbackFlagsEXT :: VkPipelineCreationFeedbackFlags;
VkSemaphoreWaitFlagsKHR :: VkSemaphoreWaitFlags;
VkAccessFlags2KHR :: VkAccessFlags2;
VkPipelineStageFlags2KHR :: VkPipelineStageFlags2;
VkAccelerationStructureMotionInfoFlagsNV :: VkFlags;
VkAccelerationStructureMotionInstanceFlagsNV :: VkFlags;
VkFormatFeatureFlags2KHR :: VkFormatFeatureFlags2;
VkMemoryDecompressionMethodFlagsNV :: VkMemoryDecompressionMethodFlagsEXT;
VkRenderingFlagsKHR :: VkRenderingFlags;
VkDirectDriverLoadingFlagsLUNARG :: VkFlags;
VkPipelineCreateFlags2KHR :: VkPipelineCreateFlags2;
VkBufferUsageFlags2KHR :: VkBufferUsageFlags2;
VkDisplayModeCreateFlagsKHR :: VkFlags;
VkDisplaySurfaceCreateFlagsKHR :: VkFlags;
VkAndroidSurfaceCreateFlagsKHR :: VkFlags;
VkViSurfaceCreateFlagsNN :: VkFlags;
VkUbmSurfaceCreateFlagsSEC :: VkFlags;
VkWin32SurfaceCreateFlagsKHR :: VkFlags;
VkXlibSurfaceCreateFlagsKHR :: VkFlags;
VkXcbSurfaceCreateFlagsKHR :: VkFlags;
VkDirectFBSurfaceCreateFlagsEXT :: VkFlags;
VkIOSSurfaceCreateFlagsMVK :: VkFlags;
VkMacOSSurfaceCreateFlagsMVK :: VkFlags;
VkMetalSurfaceCreateFlagsEXT :: VkFlags;
VkImagePipeSurfaceCreateFlagsFUCHSIA :: VkFlags;
VkStreamDescriptorSurfaceCreateFlagsGGP :: VkFlags;
VkHeadlessSurfaceCreateFlagsEXT :: VkFlags;
VkScreenSurfaceCreateFlagsQNX :: VkFlags;
VkPeerMemoryFeatureFlagsKHR :: VkPeerMemoryFeatureFlags;
VkMemoryAllocateFlagsKHR :: VkMemoryAllocateFlags;
VkCommandPoolTrimFlags :: VkFlags;
VkCommandPoolTrimFlagsKHR :: VkCommandPoolTrimFlags;
VkExternalMemoryHandleTypeFlagsKHR :: VkExternalMemoryHandleTypeFlags;
VkExternalMemoryFeatureFlagsKHR :: VkExternalMemoryFeatureFlags;
VkExternalSemaphoreHandleTypeFlagsKHR :: VkExternalSemaphoreHandleTypeFlags;
VkExternalSemaphoreFeatureFlagsKHR :: VkExternalSemaphoreFeatureFlags;
VkSemaphoreImportFlagsKHR :: VkSemaphoreImportFlags;
VkExternalFenceHandleTypeFlagsKHR :: VkExternalFenceHandleTypeFlags;
VkExternalFenceFeatureFlagsKHR :: VkExternalFenceFeatureFlags;
VkFenceImportFlagsKHR :: VkFenceImportFlags;
VkPipelineViewportSwizzleStateCreateFlagsNV :: VkFlags;
VkPipelineDiscardRectangleStateCreateFlagsEXT :: VkFlags;
VkPipelineCoverageToColorStateCreateFlagsNV :: VkFlags;
VkPipelineCoverageModulationStateCreateFlagsNV :: VkFlags;
VkPipelineCoverageReductionStateCreateFlagsNV :: VkFlags;
VkValidationCacheCreateFlagsEXT :: VkFlags;
VkDebugUtilsMessengerCreateFlagsEXT :: VkFlags;
VkDebugUtilsMessengerCallbackDataFlagsEXT :: VkFlags;
VkDeviceMemoryReportFlagsEXT :: VkFlags;
VkPipelineRasterizationConservativeStateCreateFlagsEXT :: VkFlags;
VkDescriptorBindingFlagsEXT :: VkDescriptorBindingFlags;
VkResolveModeFlagsKHR :: VkResolveModeFlags;
VkPipelineRasterizationStateStreamCreateFlagsEXT :: VkFlags;
VkPipelineRasterizationDepthClipStateCreateFlagsEXT :: VkFlags;
VkToolPurposeFlagsEXT :: VkToolPurposeFlags;
VkSubmitFlagsKHR :: VkSubmitFlags;
VkImageFormatConstraintsFlagsFUCHSIA :: VkFlags;
VkHostImageCopyFlagsEXT :: VkHostImageCopyFlags;
VkPresentScalingFlagsEXT :: VkPresentScalingFlagsKHR;
VkPresentGravityFlagsEXT :: VkPresentGravityFlagsKHR;
VkSurfaceCreateFlagsOHOS :: VkFlags;
VkPerformanceCounterDescriptionFlagsARM :: VkFlags;
VkShaderInstrumentationValuesFlagsARM :: VkFlags;
VkVideoBeginCodingFlagsKHR :: VkFlags;
VkVideoEndCodingFlagsKHR :: VkFlags;
VkVideoDecodeFlagsKHR :: VkFlags;
VkVideoEncodeRateControlFlagsKHR :: VkFlags;
VkInstance :: *VkInstance_T;
VkPhysicalDevice :: *VkPhysicalDevice_T;
VkDevice :: *VkDevice_T;
VkQueue :: *VkQueue_T;
VkCommandBuffer :: *VkCommandBuffer_T;
VkDeviceMemory :: *VkDeviceMemory_T;
VkCommandPool :: *VkCommandPool_T;
VkBuffer :: *VkBuffer_T;
VkBufferView :: *VkBufferView_T;
VkImage :: *VkImage_T;
VkImageView :: *VkImageView_T;
VkShaderModule :: *VkShaderModule_T;
VkPipeline :: *VkPipeline_T;
VkPipelineLayout :: *VkPipelineLayout_T;
VkSampler :: *VkSampler_T;
VkDescriptorSet :: *VkDescriptorSet_T;
VkDescriptorSetLayout :: *VkDescriptorSetLayout_T;
VkDescriptorPool :: *VkDescriptorPool_T;
VkFence :: *VkFence_T;
VkSemaphore :: *VkSemaphore_T;
VkEvent :: *VkEvent_T;
VkQueryPool :: *VkQueryPool_T;
VkFramebuffer :: *VkFramebuffer_T;
VkRenderPass :: *VkRenderPass_T;
VkPipelineCache :: *VkPipelineCache_T;
VkPipelineBinaryKHR :: *VkPipelineBinaryKHR_T;
VkIndirectCommandsLayoutNV :: *VkIndirectCommandsLayoutNV_T;
VkIndirectCommandsLayoutEXT :: *VkIndirectCommandsLayoutEXT_T;
VkIndirectExecutionSetEXT :: *VkIndirectExecutionSetEXT_T;
VkDescriptorUpdateTemplate :: *VkDescriptorUpdateTemplate_T;
VkDescriptorUpdateTemplateKHR :: VkDescriptorUpdateTemplate;
VkSamplerYcbcrConversion :: *VkSamplerYcbcrConversion_T;
VkSamplerYcbcrConversionKHR :: VkSamplerYcbcrConversion;
VkValidationCacheEXT :: *VkValidationCacheEXT_T;
VkAccelerationStructureKHR :: *VkAccelerationStructureKHR_T;
VkAccelerationStructureNV :: *VkAccelerationStructureNV_T;
VkPerformanceConfigurationINTEL :: *VkPerformanceConfigurationINTEL_T;
VkBufferCollectionFUCHSIA :: *VkBufferCollectionFUCHSIA_T;
VkDeferredOperationKHR :: *VkDeferredOperationKHR_T;
VkPrivateDataSlot :: *VkPrivateDataSlot_T;
VkPrivateDataSlotEXT :: VkPrivateDataSlot;
VkCuModuleNVX :: *VkCuModuleNVX_T;
VkCuFunctionNVX :: *VkCuFunctionNVX_T;
VkOpticalFlowSessionNV :: *VkOpticalFlowSessionNV_T;
VkMicromapEXT :: *VkMicromapEXT_T;
VkShaderEXT :: *VkShaderEXT_T;
VkTensorARM :: *VkTensorARM_T;
VkTensorViewARM :: *VkTensorViewARM_T;
VkDataGraphPipelineSessionARM :: *VkDataGraphPipelineSessionARM_T;
VkShaderInstrumentationARM :: *VkShaderInstrumentationARM_T;
VkDisplayKHR :: *VkDisplayKHR_T;
VkDisplayModeKHR :: *VkDisplayModeKHR_T;
VkSurfaceKHR :: *VkSurfaceKHR_T;
VkSwapchainKHR :: *VkSwapchainKHR_T;
VkDebugReportCallbackEXT :: *VkDebugReportCallbackEXT_T;
VkDebugUtilsMessengerEXT :: *VkDebugUtilsMessengerEXT_T;
VkVideoSessionKHR :: *VkVideoSessionKHR_T;
VkVideoSessionParametersKHR :: *VkVideoSessionParametersKHR_T;
VkSemaphoreSciSyncPoolNV :: *VkSemaphoreSciSyncPoolNV_T;
VkRayTracingInvocationReorderModeNV :: VkRayTracingInvocationReorderModeEXT;
VkPrivateDataSlotCreateFlagBitsEXT :: VkPrivateDataSlotCreateFlagBits;
VkDescriptorUpdateTemplateTypeKHR :: VkDescriptorUpdateTemplateType;
VkPointClippingBehaviorKHR :: VkPointClippingBehavior;
VkQueueGlobalPriorityKHR :: VkQueueGlobalPriority;
VkQueueGlobalPriorityEXT :: VkQueueGlobalPriority;
VkTimeDomainEXT :: VkTimeDomainKHR;
VkResolveModeFlagBitsKHR :: VkResolveModeFlagBits;
VkDescriptorBindingFlagBitsEXT :: VkDescriptorBindingFlagBits;
VkSemaphoreTypeKHR :: VkSemaphoreType;
VkGeometryFlagBitsNV :: VkGeometryFlagBitsKHR;
VkGeometryInstanceFlagBitsNV :: VkGeometryInstanceFlagBitsKHR;
VkBuildAccelerationStructureFlagBitsNV :: VkBuildAccelerationStructureFlagBitsKHR;
VkCopyAccelerationStructureModeNV :: VkCopyAccelerationStructureModeKHR;
VkAccelerationStructureTypeNV :: VkAccelerationStructureTypeKHR;
VkGeometryTypeNV :: VkGeometryTypeKHR;
VkRayTracingShaderGroupTypeNV :: VkRayTracingShaderGroupTypeKHR;
VkPipelineCreationFeedbackFlagBitsEXT :: VkPipelineCreationFeedbackFlagBits;
VkSemaphoreWaitFlagBitsKHR :: VkSemaphoreWaitFlagBits;
VkLineRasterizationModeKHR :: VkLineRasterizationMode;
VkLineRasterizationModeEXT :: VkLineRasterizationMode;
VkToolPurposeFlagBitsEXT :: VkToolPurposeFlagBits;
VkAccessFlagBits2KHR :: VkAccessFlagBits2;
VkPipelineStageFlagBits2KHR :: VkPipelineStageFlagBits2;
VkHostImageCopyFlagBitsEXT :: VkHostImageCopyFlagBits;
VkFormatFeatureFlagBits2KHR :: VkFormatFeatureFlagBits2;
VkRenderingFlagBitsKHR :: VkRenderingFlagBits;
VkPipelineRobustnessBufferBehaviorEXT :: VkPipelineRobustnessBufferBehavior;
VkPipelineRobustnessImageBehaviorEXT :: VkPipelineRobustnessImageBehavior;
VkDeviceFaultVendorBinaryHeaderVersionEXT :: VkDeviceFaultVendorBinaryHeaderVersionKHR;
VkMemoryDecompressionMethodFlagBitsNV :: VkMemoryDecompressionMethodFlagBitsEXT;
VkPipelineCreateFlagBits2KHR :: VkPipelineCreateFlagBits2;
VkBufferUsageFlagBits2KHR :: VkBufferUsageFlagBits2;
VkScopeNV :: VkScopeKHR;
VkComponentTypeNV :: VkComponentTypeKHR;
VkExternalMemoryHandleTypeFlagBitsKHR :: VkExternalMemoryHandleTypeFlagBits;
VkExternalMemoryFeatureFlagBitsKHR :: VkExternalMemoryFeatureFlagBits;
VkExternalSemaphoreHandleTypeFlagBitsKHR :: VkExternalSemaphoreHandleTypeFlagBits;
VkExternalSemaphoreFeatureFlagBitsKHR :: VkExternalSemaphoreFeatureFlagBits;
VkSemaphoreImportFlagBitsKHR :: VkSemaphoreImportFlagBits;
VkExternalFenceHandleTypeFlagBitsKHR :: VkExternalFenceHandleTypeFlagBits;
VkExternalFenceFeatureFlagBitsKHR :: VkExternalFenceFeatureFlagBits;
VkFenceImportFlagBitsKHR :: VkFenceImportFlagBits;
VkPeerMemoryFeatureFlagBitsKHR :: VkPeerMemoryFeatureFlagBits;
VkMemoryAllocateFlagBitsKHR :: VkMemoryAllocateFlagBits;
VkTessellationDomainOriginKHR :: VkTessellationDomainOrigin;
VkSamplerYcbcrModelConversionKHR :: VkSamplerYcbcrModelConversion;
VkSamplerYcbcrRangeKHR :: VkSamplerYcbcrRange;
VkChromaLocationKHR :: VkChromaLocation;
VkSamplerReductionModeEXT :: VkSamplerReductionMode;
VkShaderFloatControlsIndependenceKHR :: VkShaderFloatControlsIndependence;
VkSubmitFlagBitsKHR :: VkSubmitFlagBits;
VkDeviceFaultAddressTypeEXT :: VkDeviceFaultAddressTypeKHR;
VkPresentScalingFlagBitsEXT :: VkPresentScalingFlagBitsKHR;
VkPresentGravityFlagBitsEXT :: VkPresentGravityFlagBitsKHR;
VkMemoryUnmapFlagBitsKHR :: VkMemoryUnmapFlagBits;
VkDriverIdKHR :: VkDriverId;
VkCudaModuleNV :: *VkCudaModuleNV_T;
VkCudaFunctionNV :: *VkCudaFunctionNV_T;
VkExternalComputeQueueNV :: *VkExternalComputeQueueNV_T;
#scope_file
VkInstance_T :: struct {}
VkPhysicalDevice_T :: struct {}
VkDevice_T :: struct {}
VkQueue_T :: struct {}
VkCommandBuffer_T :: struct {}
VkDeviceMemory_T :: struct {}
VkCommandPool_T :: struct {}
VkBuffer_T :: struct {}
VkBufferView_T :: struct {}
VkImage_T :: struct {}
VkImageView_T :: struct {}
VkShaderModule_T :: struct {}
VkPipeline_T :: struct {}
VkPipelineLayout_T :: struct {}
VkSampler_T :: struct {}
VkDescriptorSet_T :: struct {}
VkDescriptorSetLayout_T :: struct {}
VkDescriptorPool_T :: struct {}
VkFence_T :: struct {}
VkSemaphore_T :: struct {}
VkEvent_T :: struct {}
VkQueryPool_T :: struct {}
VkFramebuffer_T :: struct {}
VkRenderPass_T :: struct {}
VkPipelineCache_T :: struct {}
VkPipelineBinaryKHR_T :: struct {}
VkIndirectCommandsLayoutNV_T :: struct {}
VkIndirectCommandsLayoutEXT_T :: struct {}
VkIndirectExecutionSetEXT_T :: struct {}
VkDescriptorUpdateTemplate_T :: struct {}
VkSamplerYcbcrConversion_T :: struct {}
VkValidationCacheEXT_T :: struct {}
VkAccelerationStructureKHR_T :: struct {}
VkAccelerationStructureNV_T :: struct {}
VkPerformanceConfigurationINTEL_T :: struct {}
VkBufferCollectionFUCHSIA_T :: struct {}
VkDeferredOperationKHR_T :: struct {}
VkPrivateDataSlot_T :: struct {}
VkCuModuleNVX_T :: struct {}
VkCuFunctionNVX_T :: struct {}
VkOpticalFlowSessionNV_T :: struct {}
VkMicromapEXT_T :: struct {}
VkShaderEXT_T :: struct {}
VkTensorARM_T :: struct {}
VkTensorViewARM_T :: struct {}
VkDataGraphPipelineSessionARM_T :: struct {}
VkShaderInstrumentationARM_T :: struct {}
VkDisplayKHR_T :: struct {}
VkDisplayModeKHR_T :: struct {}
VkSurfaceKHR_T :: struct {}
VkSwapchainKHR_T :: struct {}
VkDebugReportCallbackEXT_T :: struct {}
VkDebugUtilsMessengerEXT_T :: struct {}
VkVideoSessionKHR_T :: struct {}
VkVideoSessionParametersKHR_T :: struct {}
VkSemaphoreSciSyncPoolNV_T :: struct {}
VkCudaModuleNV_T :: struct {}
VkCudaFunctionNV_T :: struct {}
VkExternalComputeQueueNV_T :: struct {}
